[package]
name = "jenks_breaks"
version = "0.1.0"
edition = "2025"

[lib]
name = "jenks_breaks"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
numpy = "0.21"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
debug-assertions = false
